version: '2.4'
services:
    python:
        build:
            context: ..
            dockerfile: ./dockerfiles/Dockerfile-cpu
        command: jupyter lab --ip=0.0.0.0 --port=8889

    tensorboard:
        build:
            context: ..
            dockerfile: ./dockerfiles/Dockerfile-tensorflow
        volumes:
            - "..:/data"
        entrypoint: tensorboard --logdir /data/tensorboard_logs --bind_all
        ports:
            - "6006:6006"
