FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
LABEL maintainer="tranvinhcuong@gmail.com"
ENV REFRESHED_AT 2021-05-23

ENV PATH=/usr/local/cuda/bin:/home/vjai/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/

RUN apt-get -qq update && apt-get install -y --no-install-recommends \
         curl \
         wget \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 python3-pip python3-setuptools python3-dev python3-venv \
         swig mecab libmecab-dev mecab-ipadic-utf8 git xz-utils file graphviz \
         dirmngr apt-transport-https lsb-release && \
         useradd -ms /bin/bash vjai

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get install -y --no-install-recommends sudo \
        nodejs && \
    git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && \
    echo yes | mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -a && \
    sed -i -E "s#dicdir =.*#dicdir = /usr/lib/x86_64-linux-gnu/mecab/dic#" /etc/mecabrc

RUN  su - vjai -c "python3 -m pip install --upgrade pip" && \
     su - vjai -c "python3 -m pip install --upgrade --user jupyterlab" && \
     su - vjai -c "python3 -m pip install mecab-python3==1.0.3 jupyterlab_execute_time" && \
    su - vjai -c "jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib" && \
    su - vjai -c "python3 -m pip install scipy ipywidgets gensim altair matplotlib pydot scikit-learn seaborn"

RUN su - vjai -c "python3 -m pip install jax jaxlib==0.1.67+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html" && \
  su - vjai -c "python3 -m pip install --upgrade trax" && \
  su - vjai -c "python3 -m pip install transformers fugashi[unidic-lite] ipadic"


