FROM nvidia/cuda:10.2-devel-ubuntu18.04

ENV PATH=/usr/local/nvidia/bin:/home/vjai/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update && apt-get install -y --no-install-recommends \
         curl \
         wget \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 python3-pip python3-setuptools python3-dev \
         swig mecab libmecab-dev mecab-ipadic-utf8 git xz-utils file graphviz && \
         useradd -ms /bin/bash vjai

RUN su - vjai -c "python3 -m pip install --upgrade pip" && \
  su - vjai -c "python3 -m pip install --upgrade --user jupyterlab" && \
  su - vjai -c "python3 -m pip install scipy ipywidgets gensim altair matplotlib pydot h5py einops scikit-learn seaborn"
RUN su - vjai -c "python3 -m pip install torch torchvision torchaudio torchtext" && \
  su - vjai -c "python3 -m pip install mecab-python3==0.996.6rc2" && \
  su - vjai -c "python3 -m pip install transformers fugashi[unidic-lite] ipadic" && \
  sed -i -E "s#dicdir =.*#dicdir = /usr/lib/x86_64-linux-gnu/mecab/dic#" /etc/mecabrc

