FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         curl \
         wget \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 python3-pip python3-setuptools

RUN useradd -ms /bin/bash vjai && \
  python3 -m pip install --upgrade pip && \
  python3 -m pip install jupyterlab==3.0.4 matplotlib && \
  python3 -m pip install scipy==1.5.4 && \
  python3 -m pip install --upgrade jax jaxlib==0.1.59+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html && \
  python3 -m pip install --upgrade trax==1.3.7

ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin