FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         curl \
         wget \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 python3-pip python3-setuptools python3-dev python3-venv \
         swig mecab libmecab-dev mecab-ipadic-utf8 git xz-utils file graphviz

RUN apt-get install -y --no-install-recommends sudo && \
    git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && \
    echo yes | mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -a

RUN useradd -ms /bin/bash vjai && \
  su - vjai -c "python3 -m pip install --upgrade pip" && \
  su - vjai -c "python3 -m pip install --upgrade jupyterlab" && \
  su - vjai -c "python3 -m pip install scipy==1.5.4 ipywidgets gensim altair matplotlib pydot scikit-learn seaborn"
RUN su - vjai -c "python3 -m pip install jax==0.2.9 jaxlib==0.1.61+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html" && \
  su - vjai -c "python3 -m pip install trax==1.3.6" && \
  su - vjai -c "python3 -m pip install mecab-python3==0.996.6rc2" && \
  sed -i -E "s#dicdir =.*#dicdir = /usr/lib/x86_64-linux-gnu/mecab/dic#" /etc/mecabrc

ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin