version: '2.4'
services:
    python:
        build:
            context: ../
            dockerfile: ./dockerfiles/Dockerfile
        container_name : vjai_paper_coding
        image: "vjai/ml-tool:gpu"
        ports:
            - "8889:8889"
        volumes:
            - ".:/data"
        ipc: host
        user: vjai
        working_dir: /data
        tty: true
