FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

ENV PATH=/usr/local/nvidia/bin:/home/vjai/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update && apt-get install -y --no-install-recommends \
         curl \
         wget \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         python3 python3-pip python3-setuptools python3-dev python3-venv \
         swig mecab libmecab-dev mecab-ipadic-utf8 git xz-utils file graphviz && \
         useradd -ms /bin/bash vjai

RUN python3 -m pip install --upgrade pip && \
  su - vjai -c "python3 -m pip install --upgrade --user jupyterlab" && \
  python3 -m pip install scipy ipywidgets gensim altair matplotlib pydot scikit-learn ipywidgets gensim altair matplotlib pydot
RUN python3 -m pip install tensorflow-gpu tensorflow_data_validation[visualization] && \
    python3 -m pip install mecab-python3==0.996.6rc2 && \
    sed -i -E "s#dicdir =.*#dicdir = /usr/lib/x86_64-linux-gnu/mecab/dic#" /etc/mecabrc && \
    cd /usr/local/cuda/lib64 && ln libcusolver.so.11 libcusolver.so.10

ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64